spring:
  application:
    name: zhongdayun-zuul
    
server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: zhongdayun-feign
    api-b:
      path: /api-b/**
      serviceId: service-feign